CREATE DATABASE banco;
USE banco;

CREATE TABLE clientes (id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
cidade VARCHAR(50) NOT NULL,
estado VARCHAR(50) NOT NULL,
foto VARCHAR(50) NOT NULL,
PRIMARY KEY (id)) ENGINE = InnoDB;